[metadata]
name = yaml2toml
version = 1.1.0
author = Justin "Boonie Pepper" Hill
author_email = justin@so.dang.cool
description = Convert YAML to TOML
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/booniepepper/yaml2toml
project_urls =
    Bug Tracker = https://github.com/booniepepper/yaml2toml/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
scripts =
    yaml2toml
install_requires =
    pyyaml
    toml

