#!/usr/bin/env python3

import argparse
import re
import yaml
import toml

parser = argparse.ArgumentParser(description='Convert YAML to TOML.')
parser.add_argument('file', metavar='FILE', type=str, help='file to convert')
parser.add_argument('dest', metavar='DEST', type=str, help='destination filename (optional)')

args = parser.parse_args()

yaml_filename = args.file
toml_filename = args.dest or (re.sub(r'\.ya?ml$', '', yaml_filename) + '.toml')

with open(yaml_filename, 'r') as file:
    file_contents = yaml.safe_load(file)

with open(toml_filename, 'w') as file:
    toml.dump(file_contents, file)
